// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/[module]" | "/dashboard/api-keys" | "/dashboard/profile" | "/dashboard/users/create" | "/login" | "/portal" | "/portal/login" | "/portal/payments" | "/portal/policies/[id]" | "/portal/profile" | "/portal/register" | "/portal/request-change"
type AppRouteHandlerRoutes = "/api/[module]" | "/api/admin/api-keys" | "/api/admin/policyholders" | "/api/admin/users" | "/api/auth/confirm-email" | "/api/documents/generate" | "/api/export" | "/api/import" | "/api/portal/register-complete" | "/api/portal/request-change" | "/api/rating/calculate" | "/auth/login" | "/auth/logout"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard" | "/portal"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/[module]": { "module": string; }
  "/api/admin/api-keys": {}
  "/api/admin/policyholders": {}
  "/api/admin/users": {}
  "/api/auth/confirm-email": {}
  "/api/documents/generate": {}
  "/api/export": {}
  "/api/import": {}
  "/api/portal/register-complete": {}
  "/api/portal/request-change": {}
  "/api/rating/calculate": {}
  "/auth/login": {}
  "/auth/logout": {}
  "/dashboard": {}
  "/dashboard/[module]": { "module": string; }
  "/dashboard/api-keys": {}
  "/dashboard/profile": {}
  "/dashboard/users/create": {}
  "/login": {}
  "/portal": {}
  "/portal/login": {}
  "/portal/payments": {}
  "/portal/policies/[id]": { "id": string; }
  "/portal/profile": {}
  "/portal/register": {}
  "/portal/request-change": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
  "/portal": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
