import { ModuleConfig } from "@/lib/types";

export const modules: ModuleConfig[] = [
  {
    key: "users",
    label: "Users",
    description: "Profiles and role assignments for platform users",
    table: "user_profiles",
    primaryColumns: ["full_name", "role", "email", "status"],
    allowedRoles: ["admin", "compliance"],
  },
  {
    key: "policies",
    label: "Policies",
    description: "Policy lifecycle, status, and premium overview",
    table: "policies",
    primaryColumns: ["policy_number", "line_of_business", "status", "effective_date", "annual_premium"],
    allowedRoles: ["admin", "underwriter", "broker", "viewer", "compliance"],
  },
  {
    key: "quotes",
    label: "Quotes",
    description: "Quote-to-bind pipeline",
    table: "quotes",
    primaryColumns: ["quote_number", "status", "valid_until", "quoted_premium"],
    allowedRoles: ["admin", "underwriter", "broker", "viewer"],
  },
  {
    key: "payments",
    label: "Payments",
    description: "Collections, installments, and reconciliation",
    table: "payments",
    primaryColumns: ["transaction_reference", "amount", "status", "paid_at", "method"],
    allowedRoles: ["admin", "finance", "broker", "viewer"],
  },
  {
    key: "claims",
    label: "Claims",
    description: "FNOL and claims status tracking",
    table: "claims",
    primaryColumns: ["claim_number", "status", "loss_date", "reserve_amount"],
    allowedRoles: ["admin", "claims", "underwriter", "viewer"],
  },
  {
    key: "documents",
    label: "Documents",
    description: "Policy forms, evidence, and generated files",
    table: "documents",
    primaryColumns: ["document_name", "document_type", "version", "created_at"],
    allowedRoles: ["admin", "underwriter", "broker", "compliance", "viewer"],
  },
  {
    key: "underwriting",
    label: "Underwriting",
    description: "Risk reviews and decision logs",
    table: "underwriting_decisions",
    primaryColumns: ["decision_status", "risk_score", "decision_date", "reasoning"],
    allowedRoles: ["admin", "underwriter", "viewer", "compliance"],
  },
  {
    key: "commissions",
    label: "Commissions",
    description: "Broker and agent commission statements",
    table: "commissions",
    primaryColumns: ["commission_type", "amount", "status", "due_date"],
    allowedRoles: ["admin", "finance", "broker", "viewer"],
  },
  {
    key: "reports",
    label: "Reports",
    description: "Generated operational and KPI reports",
    table: "report_runs",
    primaryColumns: ["report_name", "report_type", "status", "generated_at"],
    allowedRoles: ["admin", "underwriter", "finance", "compliance", "viewer"],
  },
  {
    key: "notifications",
    label: "Notifications",
    description: "System and workflow notifications",
    table: "notifications",
    primaryColumns: ["channel", "subject", "status", "scheduled_for"],
    allowedRoles: ["admin", "underwriter", "broker", "claims", "finance", "compliance", "viewer"],
  },
  {
    key: "workflows",
    label: "Workflows",
    description: "Configurable approval and assignment rules",
    table: "workflows",
    primaryColumns: ["name", "workflow_type", "status", "version"],
    allowedRoles: ["admin", "underwriter", "compliance", "viewer"],
  },
  {
    key: "products",
    label: "Products",
    description: "Insurance product and rate model definitions",
    table: "products",
    primaryColumns: ["name", "line_of_business", "state", "status"],
    allowedRoles: ["admin", "underwriter", "broker", "viewer"],
  },
  {
    key: "carriers",
    label: "Carriers",
    description: "Carrier relationship and contract metadata",
    table: "carriers",
    primaryColumns: ["name", "naic_code", "state", "status"],
    allowedRoles: ["admin", "underwriter", "broker", "viewer"],
  },
  {
    key: "brokers",
    label: "Brokers",
    description: "Agency and producer records",
    table: "brokers",
    primaryColumns: ["agency_name", "license_number", "status", "state"],
    allowedRoles: ["admin", "underwriter", "broker", "viewer"],
  },
  {
    key: "compliance",
    label: "Compliance",
    description: "Regulatory rule checks and form compliance",
    table: "compliance_rules",
    primaryColumns: ["rule_name", "jurisdiction", "severity", "active"],
    allowedRoles: ["admin", "compliance", "underwriter", "viewer"],
  },
  {
    key: "integrations",
    label: "Integrations",
    description: "Third-party integration status and health",
    table: "integrations",
    primaryColumns: ["name", "provider", "status", "last_sync_at"],
    allowedRoles: ["admin", "underwriter", "finance", "viewer"],
  },
  {
    key: "analytics",
    label: "Analytics",
    description: "Business intelligence snapshots",
    table: "analytics_snapshots",
    primaryColumns: ["metric_name", "metric_value", "recorded_at", "dimension"],
    allowedRoles: ["admin", "underwriter", "finance", "compliance", "viewer"],
  },
  {
    key: "renewals",
    label: "Renewals",
    description: "Renewal opportunities and retention",
    table: "renewals",
    primaryColumns: ["renewal_status", "expiry_date", "renewal_premium", "renewal_score"],
    allowedRoles: ["admin", "underwriter", "broker", "viewer"],
  },
  {
    key: "endorsements",
    label: "Endorsements",
    description: "Mid-term policy changes",
    table: "endorsements",
    primaryColumns: ["endorsement_type", "status", "effective_date", "premium_impact"],
    allowedRoles: ["admin", "underwriter", "broker", "viewer"],
  },
];

export function getModuleByKey(key: string) {
  return modules.find((module) => module.key === key);
}

