var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/portal/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__c315e13e._.js")
R.c("server/chunks/ssr/_57f0770c._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/node_modules_927b6c11._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09274222._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e82ee19._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_app_layout_tsx_cc8184fa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_portal_layout_tsx_56c670ae._.js")
R.c("server/chunks/ssr/_next-internal_server_app_portal_page_actions_245a7fa2.js")
R.m(7741)
module.exports=R.m(7741).exports
