var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/users/create/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__6feba7dc._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_837f2ec7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09274222._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e82ee19._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_app_layout_tsx_cc8184fa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_0e9aa1ed._.js")
R.c("server/chunks/ssr/node_modules_927b6c11._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_users_create_page_actions_7c3020e2.js")
R.m(88791)
module.exports=R.m(88791).exports
